### ISSUE TITLE
Select OS

### ISSUE THREAD

**Issue by UH-Nerion** [solusio/solusiovps#12]
In SolusIO you have a OS with subversios like

Ubuntu
> Subversion: 18.04
> Subversion: 20.04

But in WHMCS it's not possible to select this subversion.
It's only possible to set "Ubuntu".

**Comment by JuergenLeber** [comment]
It displays OsId instead of OsImageId - Will be fixed soon

**Comment by laurisb** [comment]
Fixed in v1.0.3
