### ISSUE TITLE
OS overrides Application Selection

### ISSUE THREAD

**Issue by lonesync** [solusio/solusiovps#24]
Hello,

Within latest v1.1.0 release, Applications is now available however OS Default overrides App selection.  App menu has a 'none' option to allow for default OS, however OS does not have a 'none' option to allow for default App.

At least this is the only conclusion I can see that would not allow App to install, as changing default OS corresponds with install.

**Comment by UH-Nerion** [comment]
Same for Location, it was overwritten with some numbering value.

**Comment by UH-Nerion** [comment]
And Backup allowed, was overwritten with backup not allowed.

If you bring upgrades, please make sure that existing customers will not be affected. Upgrades must work all the time without any issues. Without this sure, we can not use it in production.

**Comment by laurisb** [comment]
@lonesync As per README: "If an application is selected then the operating system is ignored." but to minimize confusion the v1.1.2 will have "(None)" also for operating systems.

**Comment by laurisb** [comment]
@UH-Nerion Yes, this is a BC break but was done intentionally as application support is a significant new feature. So, in this case, we decided to reorder module configuration fields by importance.
