### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by JayIdealApps** [solusio/solusiovps#28]
We have an API error in WHMCS when creating an instance

**Module Command Error**
Client error response [url] https://[hostname]/api/v1/users/1 [status code] 422 [reason phrase] Unprocessable Entity

**Comment by lonesync** [comment]
Had same error happen and this related to domain field, entering a generic hostname without domain format presented error.  Entering domain format (domain.com) or (sub.domain.com) corrected with successful corresponding hostname on server.  Server hostname will be name prior to (.com) for domain and sub-name in sub.domain format.

**Comment by JayIdealApps** [comment]
@lonesync Have tried test.test.com and test.com but getting the same error.

**Comment by lonesync** [comment]
Interesting, what version are you running?  Running v1.1.1 here, was hopeful this would be a solution for you as well.  Does make one curious as to what could be triggering...

**Comment by lonesync** [comment]
Actually, one other scenario was using Admin email in testing.

**Comment by JayIdealApps** [comment]
@lonesync Using the latest 1.1.2
Yes, I'm using the admin email as a user too.

**Comment by ryanpek** [comment]
If the user enters a bad hostname, it should just set a random one.  Its pretty sensitive.

I mean hostnames in admin are 'trevion-op8nta' what does it matter if its yourdomain.com?

**Comment by lonesync** [comment]
Would be nice to have an error come back with an appropriate correction message for the user.

True one could go with random naming, it's just nice to have a matching hostname/domain -  when looking through multi servers it's quick to spot the desired server.  Random names do lead to mistakes when deleting, along with billing questions - matching across the board makes things much smoother overall.

**Comment by laurisb** [comment]
Fixed in v1.1.3.
