### ISSUE TITLE
change hostname

### ISSUE THREAD

**Issue by ryanpek** [solusio/solusiovps#31]
The hostname changes do not take place until the VM is stopped manually. Rebooting from inside the vm doesn't trigger cloudinit to change hostname.  Tested on Centos.

The whmcs change hostname button should shutdown the vm  and warn user prior to fully update the hostname on the OS + SolusIO panel + Whmcs. 

Thanks
Ryan

**Comment by laurisb** [comment]
Fixed in v1.2.2
