### ISSUE TITLE
Reinstall

### ISSUE THREAD

**Issue by JayIdealApps** [solusio/solusiovps#32]
Hello

When pressing the reinstall button from the user end, it popups modal without content.

**Comment by laurisb** [comment]
Can you provide a screenshot? Any errors in the DevTools Console?

**Comment by JayIdealApps** [comment]
When clicking, it popups confirmation alert screen. After clicking to OK it gives this screen https://prnt.sc/vd8ax4

**Comment by Kubik-Rubik** [comment]
Can you please provide the Firefox version and installed add-ons?

Please also try it with another browser like Chrome. Can you reproduce the same behaviour?

Thank you for helping us in improving our solution!

**Comment by JayIdealApps** [comment]
FireFox 82.0
Chrome 86.0

I have checked both of them.

**Comment by laurisb** [comment]
I presume this is the same issue as in #37 so closing it now. Please reopen if the issue persists even after complete module installation.
