### ISSUE TITLE
File Chart.js not included

### ISSUE THREAD

**Issue by JayIdealApps** [solusio/solusiovps#37]
![image](https://user-images.githubusercontent.com/12204230/99896437-ebacd600-2ca9-11eb-9edb-d22c8291979e.png)

**Comment by laurisb** [comment]
As you can see in the screenshot below, your module installation is either incomplete or corrupted. Try to install the latest release again.

![screenshot](https://user-images.githubusercontent.com/2082155/100069821-74a64780-2e39-11eb-912f-11d2aebd1895.png)
