### ISSUE TITLE
Cron Completion error WHMCS

### ISSUE THREAD

**Issue by AlexPads** [solusio/solusiovps#42]
Hello, I am using the latest released version of the VPS module, and when my WHMCS automated cron runs it crashes with this error. 

https://pastebin.com/V4vRCgL9

Thank you,

**Comment by AlexPads** [comment]
We actually found a fix ourselves and deployed that on our services. The error is that the server it is trying to terminate was either already gone or missing or something and the termination cycle would error out. We found out that the error message itself is what was causing the errors to occur. We have fixed it in our local build by just replacing the error message with plain text for now.

**Comment by oneumyvakin** [comment]
Should be fixed since v1.2.5 by #47
