### ISSUE TITLE
Password reset doesn't send email to clients

### ISSUE THREAD

**Issue by ryanpek** [solusio/solusiovps#44]
When password reset is issued it wont email the client.  

I have no issues doing it under the admin login via the control panel.

**Comment by oneumyvakin** [comment]
Hi @ryanpek , we would like to collect more information about this issue, like steps to reproduce the issue, environment details, etc. To avoid exposure of sensitive data that could be in logs, consider to submit a ticket on our support portal https://support.solus.io/hc/en-us . If for some reason you have troubles with a ticket submission, let me know. Please note it will require you to sign-in to Solus Help Center to create a ticket.

**Comment by oneumyvakin** [comment]
Hi @ryanpek this issue have to be fixed in SolusIO version 1.1.17524.
