### ISSUE TITLE
SSO to Solus.IO

### ISSUE THREAD

**Issue by UH-Nerion** [solusio/solusiovps#8]
Hello,

it should be possible to activate/deactivate SSO to Solus.IO control panel from Customer WHMCS GUI.

**Comment by JuergenLeber** [comment]
Currently mixing up customers with pre and post paid products isn't supported so no login to SolusIO should be possible for WHMCS provisioned customers. We'll probably work on that in future but no ETA yet.

**Comment by UH-Nerion** [comment]
Sorry I don't understand this.
Why no SSO to Solus.IO, so customer can just manage his service there. Not doing any products upgrades. Just having the full range of management options.

Or are you going to add all management features to WHMCS directly? If yes, then you are right, no SSO is needed.

**Comment by JuergenLeber** [comment]
Currently the user would be able to change the settings of the (via WHMCS) created server then in SolusIO, too which should not be possible. In future the user will be able to additionally log into SolusIO and even create post-paid servers there in addition to the pre paid ones from WHMCS. Changing settings on the pre paid ones will only be possible via WHMCS then. The module will also get features like graphs in future to make customers able to control everything from there.

**Comment by UH-Nerion** [comment]
Great. So in this case you can close this case.
