### ISSUE TITLE
New update doesn't reinstall

### ISSUE THREAD

**Issue by jackrhenderson** [solusio/solusiovps#81]
I don't know if you guys have tested this on WHMCS or not but when I moved everything over my clients are unable to reinstall to an application or an operating system.

**Comment by vss414** [comment]
Hello.
I'm really sorry that our last update contained bugs. We will fix it tomorrow in this PR - https://github.com/solusio/solusiovps/pull/82
Our goal in that update was support applications during reinstall, so we concentrated to it and didn't test OS.
You mentioned that your clients were unable to reinstall to an application - could you provide more information about this problem?

**Comment by CatalystVM** [comment]
Hi thanks for getting back to me. 
So when I was doing my tests I was unable to provision a server with an application. I was also unable to reinstall in general, I was trying to reinstall to an application but it wasn't working so I decided to test operating system and it was not working as well. I wonder if it has something to do with the modal sending the correct commands maybe?

Anyways, thanks for the response. I hope to see a fix soon.

**Comment by CatalystVM** [comment]
> Hello.
> I'm really sorry that our last update contained bugs. We will fix it tomorrow in this PR - #82
> Our goal in that update was support applications during reinstall, so we concentrated to it and didn't test OS.
> You mentioned that your clients were unable to reinstall to an application - could you provide more information about this problem?

I went through and moved the latest PR to my server and the updates seem to be working just fine
