### ISSUE TITLE
Recreate VM

### ISSUE THREAD

**Issue by UH-Nerion** [solusio/solusiovps#9]
The option to recreate a VM is missing.

From Admin View it should be possible to define OS templates that are available for recreation.

So for example if customer has ordered a Linux VPS, it should not be possible to select a Windows Template during recreation.

**Comment by JuergenLeber** [comment]
Servers can just be reinstalled and keep their MAC/IP and size

**Comment by UH-Nerion** [comment]
Yes I know this.
But we need that customer can select a OS. Please create it as feature request.

**Comment by JuergenLeber** [comment]
Okay, got it!

**Comment by laurisb** [comment]
This is already implemented, but not enabled by default. To make it work you need to allow customer select operating system by defining configurable option "Operating System" and assigning it to product. Then the user will be presented with choice of operating systems before recreating VM.

![Screenshot 2020-09-16 093719](https://user-images.githubusercontent.com/2082155/93306510-41738680-f800-11ea-816c-8066ffa4f6c1.png)
